# The URL the site will be built for
base_url = "https://example.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Gutenberg
highlight_code = true

[extra]
# Put all your custom variables here
portfolio_tracking_id = "UA-123456-4"
# portfolio_ackee_id = ""
# portfolio_ackee_server = ""
# theme = "dark"
portfolio_name = "Alexander Lozada"
portfolio_description = "Hi"
portfolio_contact = "#"
